import type { Config } from "tailwindcss";

export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {

        primary: {
          main: '#2E8DFF',
          surface: '#F5F5FF',
          border: '#DFE0F3',
          hover: '#1463FF',
          pressed: '#085885',
          focus: '#4C4DDC33',
        },
        secondary: {
          main: '#FFD33C',
          surface: '#FFF6D8',
          border: '#FFF0BE',
          hover: '#D5B032',
          pressed: '#806A1E',
          focus: '#FFF6D8',
        },
        success: {
          main: '#50CD89',
          surface: '#F2FFF8',
          border: '#C5EED8',
          hover: '#46B277',
          pressed: '#28593F',
          focus: '#50CD8933',
        },
        error: {
          main: '#F14141',
          surface: '#FFF2F2',
          border: '#FAC0C0',
          hover: '#D93A3A',
          pressed: '#802A2A',
          focus: '#F1414133',
        },
        info: {
          main: '#7239EA',
          surface: '#F6F2FF',
          border: '#D0BDF8',
          hover: '#6633D1',
          pressed: '#3F2478',
          focus: '#7239EA33',
        },
        neutral: {
          10: '#FFFFFF',
          20: '#F5F5F5',
          30: '#EDEDED',
          40: '#CED1D8',
          50: '#AFB3BB',
          60: '#7E8492',
          70: '#606060',
          80: '#35373D',
          90: '#161A34',
          100: '#1D1E25',
        },
      },
      fontSize: {
        h1: ['80px', '96px'],
        h1_5: ['64px', '76.8px'],
        h2: ['48px', '56px'],
        h2_5: ['56px', '68px'],
        h3: ['40px', '48px'],
        h3_5: ['40px', '52px'],
        h4: ['32px', '40px'],
        h4_5: ['32px', '48px'],
        h5: ['24px', '34px'],
        h6: ['20px', '26px'],
        extralarge: ['18px', '32px'],
        large: ['16px', '24px'],
        largeplus: ['16px', '26px'],
        medium: ['14px', '20px'],
        small: ['12px', '16px'],
      },
      keyframes: {
        slideInMenu: {
          '0%': { transform: 'translateX(100%)', right: '-400px' },
          '50%': { trasform: 'translateX(0)', right: '-50px' },
          '100%': { transform: 'translateX(-50%)', right: '0' },
        },
        slideOutMenu: {
          '0%': { transform: 'translateX(-50%)', right: '0' },
          '50%': { trasform: 'translateX(0)', right: '-50px' },
          '100%': { transform: 'translateX(100%)', right: '-400px' },
        },
        slideRight: {
          '0%': { transform: 'translateX(-150%)', opacity: '0' },
          '25%': { transform: 'translateX(-100%)', opacity: '0.25' },
          '50%': { transform: 'translateX(-50%)', opacity: '0.5'},
          '75%': { transform: 'translateX(-25%)', opacity: '0.75'},
          '100%': { transform: 'translateX(0)', opacity: '1'},
        },
        slideLeft: {
          '0%': { transform: 'translateX(150%)', opacity: '0' },
          '25%': { transform: 'translateX(100%)', opacity: '0.25' },
          '50%': { transform: 'translateX(50%)', opacity: '0.5'},
          '75%': { transform: 'translateX(25%)', opacity: '0.75'},
          '100%': { transform: 'translateX(0)', opacity: '1'},
        },
        slideUp: {
          '0%': { transform: 'translateY(150%)', opacity: '0' },
          '25%': { transform: 'translateY(100%)', opacity: '0.25' },
          '50%': { transform: 'translateY(50%)', opacity: '0.5'},
          '75%': { transform: 'translateY(25%)', opacity: '0.75'},
          '100%': { transform: 'translateY(0)', opacity: '1'},
        },
        slideDown: {
          '0%': { transform: 'translateY(-150%)', opacity: '0' },
          '25%': { transform: 'translateY(-100%)', opacity: '0.25' },
          '50%': { transform: 'translateY(-50%)', opacity: '0.5'},
          '75%': { transform: 'translateY(-25%)', opacity: '0.75'},
          '100%': { transform: 'translateY(0)', opacity: '1'},
        },
        slideDownSl: {
          '0%': { transform: 'translateY(-50%)', opacity: '0' },
          '25%': { transform: 'translateY(-35%)', opacity: '0.25' },
          '50%': { transform: 'translateY(-25%)', opacity: '0.5'},
          '75%': { transform: 'translateY(-15%)', opacity: '0.75'},
          '100%': { transform: 'translateY(0)', opacity: '1'},
        },
        slideRightSl: {
          '0%': { transform: 'translateX(-50%)', opacity: '0' },
          '25%': { transform: 'translateX(-35%)', opacity: '0.25' },
          '50%': { transform: 'translateX(-25%)', opacity: '0.5'},
          '75%': { transform: 'translateX(-15%)', opacity: '0.75'},
          '100%': { transform: 'translateX(0)', opacity: '1'},
        },
        slideLeftSl: {
          '0%': { transform: 'translateX(50%)', opacity: '0' },
          '25%': { transform: 'translateX(35%)', opacity: '0.25' },
          '50%': { transform: 'translateX(25%)', opacity: '0.5'},
          '75%': { transform: 'translateX(15%)', opacity: '0.75'},
          '100%': { transform: 'translateX(0)', opacity: '1'},
        },
        rotate: {
          '0%': { transform: 'rotate(180deg)' },
          '25%': { transform: 'rotate(120deg)' },
          '50%': { transform: 'rotate(90deg)' },
          '75%': { transform: 'rotate(60deg)' },
          '100%': { transform: 'rotate(30deg)' },
        },
        fadeIn: {
          '0%': { opacity: '1' },
          '25%': { opacity: '0.8' },
          '50%': { opacity: '0.6'},
          '75%': { opacity: '0.4'},
          '100%': { opacity: '0.2'},
        },
        fadeOut: {
          '0%': { opacity: '0' },
          '25%': { opacity: '0.25' },
          '50%': { opacity: '0.5'},
          '75%': { opacity: '0.75'},
          '100%': { opacity: '1'},
        },
      },

    },
  },
  plugins: [],
} satisfies Config;
